### ISSUE TITLE
create good readme.md

### ISSUE THREAD

**Issue by ayaan-qadri** [PentW0lf/EdRemover#1]

**Comment by riyaku11** [comment]
I would work on this, Please assign me

**Comment by ayaan-qadri** [comment]
try to create some graphical representation.

**Comment by riyaku11** [comment]
okay @PentW0lf

**Comment by dharmikjethva30** [comment]
i can take up this one!

**Comment by ayaan-qadri** [comment]
sure, you can go for it @dharmikjethva30
